chamados_gerais/urls.py
from unicodedata import name
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = "chamado_geral"

urlpatterns = [
    path('', views.chamadosList, name='chamados-list'),
    path('chamado_geral/<int:id>', views.chamadoView, name="chamado-view"),
    path('newChamado/', views.newChamado, name='new-chamado'),
    path('chamadosGerais/', views.chamadosGerais, name='chamadosGerais'),
    path('edit/<int:id>', views.editChamado, name='edit-chamado'),
    path('edit2/<int:id>', views.editChamado2, name='edit-chamado2'),
    path('delete/<int:id>', views.deleteChamado, name='delete-chamado'),
    path('midia/', views.midia, name="midia"),
    path('midia2/', views.midia2, name="midia2"),
    path('admin2/', views.admin2, name='admmin-acess'),
    path('admin3/', views.admin3, name='admmin-acess3'),
]


if settings.DEBUG: 
    urlpatterns += static(
        settings.MEDIA_URL, 
        document_root = settings.MEDIA_ROOT
    )

todo/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include
#from chamados.settings import MEDIA_ROOT, MEDIA_URL
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chamados_gerais.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

#if settings.DEBUG:
 #   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
  #  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

chamados_gerais/models.py
from turtle import title
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here. esse

class Chamado_geral(models.Model):

    STATUS = (
        ('Solicitado', 'Solicitado'),       # Solicitado
        ('Em_andamento', 'Em_andamento'),   # em andamento
        ('Concluído', 'Concluído'),         # concluido
      
    )

    titulo = models.CharField("Título:", max_length=255)
    descrição = models.TextField("Descrição:")
    arquivo = models.FileField("Anexo:", upload_to='',  blank=True, null=True)
    Status = models.CharField(
        max_length=20,
        choices=STATUS,
    )

    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, blank=True, null=True)
    #com esse comando abaixo pegamos a data da solicitação
    created_at = models.DateTimeField(auto_now_add=True)
    # o comando abaixo serve para sempre que alguém alterar o status o db seja atualizado de acordo
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.titulo #com isso no painel terá o título em cada chamado.



        #testes testes

chamados_gerais/forms.py
from dataclasses import field
from django import forms

from .models import Chamado_geral

class ChamadoForm(forms.ModelForm):
    class Meta:
        model = Chamado_geral
        fields = ('titulo', 'descrição')


class ChamadoForm2(forms.ModelForm):
    class Meta:
        model = Chamado_geral
        fields = ('titulo', 'descrição', 'arquivo', 'Status')
    #Arquivo = forms.FileField(
     #   label='Selecione um anexo',
     #   help_text='max. 42 megabytes'
    #)

chamados_gerais/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404, redirect
from django.http import HttpResponse 
from django.http import HttpResponseRedirect  
#from urllib import request
from .forms import ChamadoForm, ChamadoForm2
from django.contrib import messages
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage #import para visualizar anexos
from django.contrib import admin
#from projeto3.myapp.models import Author
import logging
from . import models

from django.shortcuts import render
from .forms import Chamado_geral

from .models import Chamado_geral

from .forms import ChamadoForm2

#como fazer deploy: https://www.treinaweb.com.br/blog/deploy-de-uma-aplicacao-django-no-heroku  hahahah

# Create your views here.
@login_required
def chamadosList(request): #request é a requisição do django
    chamados_list = Chamado_geral.objects.all().order_by('-created_at').filter(user=request.user)  #Pegando todas os chamados do banco para o template.

    paginator = Paginator(chamados_list, 10)
    page = request.GET.get('page')
    chamados = paginator.get_page(page)

    return render(request, 'chamados/list.html', {'chamados': chamados})
   

@login_required
def chamadoView(request, id):
    chamado_geral = get_object_or_404(Chamado_geral, pk=id)
    return render(request, 'chamados/chamado.html', {'chamado': chamado_geral})

@login_required
def newChamado(request):
    if request.method == 'POST':
        form = ChamadoForm(request.POST)

        if form.is_valid():
            chamado_geral = form.save(commit=False) #commit=False serve para que o form só envie dados pro banco após clicar no botão de solicitar.
            chamado_geral.Status = 'Solicitado' #pr-e preenchido com status 'solicitado'
            chamado_geral.user = request.user
            chamado_geral.save()
            messages.info(request, 'Chamado aberto com sucesso!')
            return redirect('/') #/ = nossa primeira página

    else:
        form = ChamadoForm()
        return render(request, 'chamados/addChamado.html', {'form': form})

@login_required
def deleteChamado(request, id):
    chamado = get_object_or_404(Chamado_geral, pk=id)
    chamado.delete()
    messages.info(request, 'Chamado deletado com sucesso!')
    return redirect('/')

@login_required
def editChamado(request, id):
    chamado = get_object_or_404(Chamado_geral, pk=id)
    form = ChamadoForm(instance=chamado)

    if(request.method == 'POST'):
        form = ChamadoForm(request.POST, instance=chamado)

        if(form.is_valid()):
            chamado.save()
            messages.info(request, 'Editado com sucesso!')
            return redirect('/')
        else:
            return render(request, 'chamados/editChamado.html', {'form': form, 'chamado': chamado})
    else:
        return render(request, 'chamados/editChamado.html', {'form': form, 'chamado': chamado})

@login_required
def editChamado2(request, id):
    chamado = get_object_or_404(Chamado_geral, pk=id)
    form = ChamadoForm2(instance=chamado)
    
    if(request.method == 'POST'):
        form = ChamadoForm2(request.POST, instance=chamado) #form = ChamadoForm2(request.POST, request.FILES) tentativa de resolver bug 

        if(form.is_valid()):
            #chamado = form.save(commit=False) #commit=False serve para que o form só envie dados pro banco após clicar no botão de solicitar.
            #chamado.user = request.user
            #chamado = form.save(commit=False)
           # arquivo = request.FILES['document']
            #print(chamado.Arquivo.name)
           # print(chamado.Arquivo.size)
            #ChamadoForm2(request.FILES['Arquivo'])
            titulo = request.POST["Título"]
            descrição = request.POST["Descrição"]   
            arquivo = request.FILES["Arquivo"]
            status = request.POST["Status"]

            chamado = models.Chamado_geral(
                Título = titulo,
                Descrição = descrição,
                Arquivo = arquivo,
                Status = status

            )
            chamado.save()
            #print('arquivo teste: ', chamado.Arquivo)
            #logging.info('bug:')
            messages.info(request, 'Chamado editado com sucesso!')
            return redirect('/admin3/')
        else:
            return render(request, 'chamados/edit2.html', {'form': form, 'chamado': chamado})
    else:
        return render(request, 'chamados/edit2.html', {'form': form, 'chamado': chamado})

@login_required
def editChamado3(request, id):

    chamado = get_object_or_404(Chamado_geral, pk=id)
    form = ChamadoForm2(instance=chamado)
    
    if(request.method == 'POST'):
        form = ChamadoForm2(request.POST, instance=chamado) #form = ChamadoForm2(request.POST, request.FILES) tentativa de resolver bug 

        if(form.is_valid()):
            #chamado = form.save(commit=False) #commit=False serve para que o form só envie dados pro banco após clicar no botão de solicitar.
            #chamado.user = request.user
            #chamado = form.save(commit=False)
           # arquivo = request.FILES['document']
            #print(chamado.Arquivo.name)
           # print(chamado.Arquivo.size)
            #ChamadoForm2(request.FILES['Arquivo'])
            titulo = request.POST["Título"]
            descrição = request.POST["Descrição"]
            arquivo = request.FILES["Arquivo"]
            status = request.POST["Status"]

            chamado = models.Chamado_geral(
                Título = titulo,
                Descrição = descrição,
                Arquivo = arquivo,
                Status = status

            )
            chamado.save()
            #print('arquivo teste: ', chamado.Arquivo)
            #logging.info('bug:')
            messages.info(request, 'Chamado editado com sucesso!')
            return redirect('/admin3/')
        else:
            return render(request, 'chamados/edit2.html', {'form': form, 'chamado': chamado})
    else:
        return render(request, 'chamados/edit2.html', {'form': form, 'chamado': chamado})


@login_required
def chamadosGerais(request):
    chamados = Chamado_geral.objects.all().order_by('-created_at')
    paginator = Paginator(chamados, 10)
    page = request.GET.get('page')
    chamados = paginator.get_page(page)

    return render(request, 'chamados/chamadosGerais.html', {'chamados': chamados})

@login_required
def midia(request):
    if request.method == 'POST':
        uploaded_file = request.FILES['document']
        fs = FileSystemStorage()
        fs.save(uploaded_file.name, uploaded_file)
    return render(request, 'upload.html')

    
@login_required #Não está me uso
def midia2(request):
    if request.method == 'POST':
        uploaded_file = request.FILES['document']
        fs = FileSystemStorage()
        fs.save(uploaded_file.name, uploaded_file)
    return render(request)


@login_required
def admin2(request):
    if request.method == 'POST':
        form = ChamadoForm2(request.get)

        if form.is_valid():
            chamado_geral = form.save(commit=False) #commit=False serve para que o form só envie dados pro banco após clicar no botão de solicitar.
            #chamado_geral.Status = 'Solicitado' #pr-e preenchido com status 'solicitado'
            chamado_geral.user = request.user
            chamado_geral.save()
            #messages.info(request, 'Chamado aberto com sucesso!')
            return redirect('/') #/ = nossa primeira página

    else:
        form = ChamadoForm2()
        return render(request, 'chamados/admin2-upload.html', {'form': form})


@login_required
def admin3(request):

    chamados = Chamado_geral.objects.all().order_by('-created_at')
    
    paginator = Paginator(chamados, 10)
    page = request.GET.get('page')
    chamados = paginator.get_page(page)

    return render(request, 'chamados/admin3.html', {'chamados': chamados})

chamados_gerais/templates/chamados/addChamado.html
{% extends 'base2.html' %}
{% load crispy_forms_tags %}

{% block title %}Abrindo chamado{% endblock %}

{% block content %}

<style>

.ajuste{
   width: 400px;
}


</style>


 <div class=" offset-1 col-10 list-div ajuste">
   <div class="box">
      
       <!--<h2><span>Solicite um item:</span></h2>-->
       <h5 class="text-uppercase font-weight-light text-monospace">Preencha os campos abaixo!</h5>
       <br>
       
       <form  method="POST"  enctype="multipart/form-data">
          {% csrf_token %}
          {{ form|crispy }} 
          <br>
          <input type="submit" class="btn btn-primary botao text-uppercase font-weight-light text-monospace" value="Solicitar">
          <!--<button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>-->
       </form>
   </div>
</div>


{% endblock %}

chamados_gerais/templates/chamados/admin2-upload.html
{% extends 'base2.html' %}
{% load crispy_forms_tags %}

{% block title %}Admin{% endblock %}

{% block content %}

<style>

.ajuste{
   width: 400px;
}


</style>


 <div class=" offset-1 col-10 list-div ajuste">
   <div class="box">
      
       <!--<h2><span>Solicite um item:</span></h2>-->
       <h5 class="text-uppercase font-weight-light text-monospace">Admin</h5>
       <br>
       
       <form  method="POST"  enctype="multipart/form-data">
          {% csrf_token %}
          {{ form|crispy }} 
          <br>
          <input type="submit" class="btn btn-primary botao text-uppercase font-weight-light text-monospace" value="Solicitar">
          <!--<button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>-->
       </form>
   </div>
</div>


{% endblock %}

chamados_gerais/templates/chamados/admin2.html
{% extends 'base2.html' %}
{% load crispy_forms_tags %}

{% block title %}Admin{% endblock %}

{% block content %}

<style>

.ajuste{
   width: 400px;
}


</style>


 <div class=" offset-1 col-10 list-div ajuste">
   <div class="box">
      
       <!--<h2><span>Solicite um item:</span></h2>-->
       <h5 class="text-uppercase font-weight-light text-monospace">Admin</h5>
       <br>
       <form  method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form|crispy }} 
          <br>
          <input type="submit" class="btn btn-primary botao text-uppercase font-weight-light text-monospace" value="Solicitar">
          <!--<button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>-->
       </form>
   </div>
</div>


{% endblock %}

chamados_gerais/templates/chamados/admin3.html
{% extends 'base3.html' %}

{% block title %}Admin{% endblock %}

{% block content %}


<style>

/*Estilização do messages (alertas de ações)*/
    ul.messages{
        padding: 0;
    }

    ul.messages li{
        list-style: none;
    }

/*Estilização da paginação*/
.pagination{
    margin-bottom: 20px;
}

.step-links{
    position: relative;
    margin-left: auto;
    margin-right: auto;
}

.step-links .current{
    margin-left: 5px;
    margin-right: 5px;
}


/*filtro*/
.filter-div{
    margin-bottom: 15px;
    padding: 0;
}

#filter{
    display: inline-block;
    width: 200px;
    margin-left: 10px;
}

div.ajusteFiltro{
    margin-top: 25px;
    text-align: center;
}

/*dashboard*/
.dashboard{
    padding: 0;
    width: 100%;
    display: block;
}

.dashboard h4{
    font-size: 20px;
}

.dashboard span{
    font-size: 40px;
    display: block;
    width: 100%;
}

.dashboard-box{
    float: left;
    background-color: #DFDFDF;
    color: #FFF;
    padding: 20px;
    box-sizing: border-box;
    height: 130px;
    width: 32%;
    text-align: center;
}

.dashboard-box:nth-child(2){
    margin-left: 1.5%;
    margin-right: 1.5%;
}

#dashboard-lastdays{
    background-color: #3476e2;
}

#dashboard-done{
    background-color: #13c43f
}

#dashboard-doing{
    background-color:#db1e47
}

#dashboard-done2{
    background-color: #13c43f
}

.add-div {
    background-color: #3476e2;
    cursor: pointer;
    display: inline-block;
    color: #FFF;
    padding: 8px;
    border-radius: 5px;
    margin-right: 25px;
    width: 50px;
}

.fas.fa-plus{
    color: #FFF;
    margin-right: 10px;
    margin-left: 5px;
}

/*search*/
.fas.fa-search{
    position: absolute;
    top: 12px;
    right: 26px;
}

.search-div{
    padding: 0px;
    margin-top: 15px;
    margin-bottom: 15px;
    display: inline-block;
}

/*
.ajustePesquisar{
    width: 50%;
    margin-left: 188px;
}*/




div.botao{
    text-align: center;
}

</style>



<br>
<br>
<div style="text-align: center;" class="container titulo" >
    <h5 class="text-uppercase font-weight-light text-monospace">Gerenciamento de chamados internos</h5>
</div>
<br>
<br>


<div class="container" >
<a href="/" >
        
    <!-- <i class="fas fa-plus" aria-hidden="true"></i> Solicitar-->
     <button type="button" class="btn btn-primary botao text-uppercase font-weight-light text-monospace">Volte para Home</button>
 
</a>
<br>
</div>

<br>
<br>

       
            <div class="col-12 container ajustePesquisar" >
                <input class="form-control container" id="myInput" type="text" placeholder="Pesquise por registros de qualquer campo..." >
                <!--<i class="fas fa-search" ></i>-->
             </div>
        
             <br>
        
        
        
    </div>

    <br>
    <br>
    <div style="text-align: center;" class="container" >
        <h5 class="text-uppercase font-weight-light text-monospace">Listagem abaixo</h5>
    </div>
    <br>
    <br>
    <br>
 
    <div class="container" >
    <div class="tabela">
        <table class="table">
            <thead>
            <tr> 
                <th style="text-align: center;" >Solicitante</th>
                <th style="text-align: center;" >Data</th>
                <th style="text-align: center;" >Atualizado em</th>
                <th style="text-align: center;" >Título</th>
                <th style="text-align: center;" >Descrição</th>
                <th style="text-align: center;" >Status</th>
                <th style="text-align: center;" >Anexo</th>
                <th style="text-align: center;" >Ações</th>
                <th></th>
                <th></th>
                
            </tr>
            </thead>

            {% if messages %}
            <!--Messagens de alerta de interação ao editar e excluir item-->
                <ul class="messages" >
                    {% for message in messages %}
                        <li {% if message.tags  %}class="alert alert-{{message.tags}}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>

            {% endif %}

            <tbody id="myTable" class="alinhar">
     
            {% for chamado in chamados %}

            <tr>
                <td style="text-align: center;" >{{chamado.user}}</td>
                <td style="text-align: center;" >{{chamado.created_at}}</td>
                <td style="text-align: center;" >{{chamado.updated_at}}</td>
                <td style="text-align: center;" >{{chamado.Título}}</td>
                <td style="text-align: center;" >{{chamado.Descrição}}</td>
                <td style="text-align: center;" >{{chamado.Status}}</a></td>
                <td style="text-align: center;" ><a href="/midia/{{chamado.Arquivo}}" >Ver</a></td>
                <td> 
                    <a href="/edit2/{{chamado.id}}" ><button type="button" class="btn btn-primary"><i class="fas fa-pencil-alt"></i></button></a>
                </td>
               
            </tr>

            {% endfor %}

            </tbody>
        </table>

        
        <div class="pagination" >
            <span class="step-links" >
                <!--Lógica para página anterior-->
                {% if chamados.has_previous %}
                    <a href="?page={{ chamados.previous_page_number }}" ><i class="fas fa-arrow-left" ></i></a>
                {% endif %}

                <!--Span mostrando a página atual do usuário-->
                <span class="current" >
                    {{ chamados.number }} de {{ chamados.paginator.num_pages }}
                </span>

                <!--Lógica para página posterior-->
                {% if chamados.has_next %}
                    <a href="?page={{ chamados.next_page_number }}" ><i class="fas fa-arrow-right" ></i></a>
                {% endif %}
            </span>
        </div>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        
        </div>
    </div>

        <script>
            $(document).ready(function(){
            $("#myInput").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function() {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
            });
        </script>
    

{% endblock %}

chamados_gerais/templates/chamados/chamado.html
{% extends 'base.html' %}

{% block title %}Lista de tarefas{% endblock %}

{% block content %}

            <tr>
                <td>Teste</td>
                <td>Notebook acer</td>
                <td>Teste</td>
                <td>Teste</td>
                <td>Teste</td>
                <td> 
                    <button type="button" class="btn btn-primary" onclick="editar()">
                        <i class="fas fa-pencil-alt"></i>
                    </button>
                </td>
                <td>
                    <button type="button" class="btn btn-danger" onclick="excluir()">
                        <i class="fas fa-trash-alt"></i>
                    </button>
                </td>
            </tr>


{% endblock %}

chamados_gerais/templates/chamados/chamadosGerais.html
{% extends 'base.html' %}

{% block title %}Chamados gerais{% endblock %}

{% block content %}

<style>

/*Estilização do messages (alertas de ações)*/
    ul.messages{
        padding: 0;
    }

    ul.messages li{
        list-style: none;
    }

/*Estilização da paginação*/
.pagination{
    margin-bottom: 20px;
}

.step-links{
    position: relative;
    margin-left: auto;
    margin-right: auto;
}

.step-links .current{
    margin-left: 5px;
    margin-right: 5px;
}


/*filtro*/
.filter-div{
    margin-bottom: 15px;
    padding: 0;
}

#filter{
    display: inline-block;
    width: 200px;
    margin-left: 10px;
}

div.ajusteFiltro{
    margin-top: 25px;
    text-align: center;
}

/*dashboard*/
.dashboard{
    padding: 0;
    width: 100%;
    display: block;
}

.dashboard h4{
    font-size: 20px;
}

.dashboard span{
    font-size: 40px;
    display: block;
    width: 100%;
}

.dashboard-box{
    float: left;
    background-color: #DFDFDF;
    color: #FFF;
    padding: 20px;
    box-sizing: border-box;
    height: 130px;
    width: 32%;
    text-align: center;
}

.dashboard-box:nth-child(2){
    margin-left: 1.5%;
    margin-right: 1.5%;
}

#dashboard-lastdays{
    background-color: #3476e2;
}

#dashboard-done{
    background-color: #13c43f
}

#dashboard-doing{
    background-color:#db1e47
}

#dashboard-done2{
    background-color: #13c43f
}

.add-div {
    background-color: #3476e2;
    cursor: pointer;
    display: inline-block;
    color: #FFF;
    padding: 8px;
    border-radius: 5px;
    margin-right: 25px;
    width: 50px;
}

.fas.fa-plus{
    color: #FFF;
    margin-right: 10px;
    margin-left: 5px;
}

/*search*/
.fas.fa-search{
    position: absolute;
    top: 12px;
    right: 26px;
}

.search-div{
    padding: 0px;
    margin-top: 15px;
    margin-bottom: 15px;
    display: inline-block;
}

/*
.ajustePesquisar{
    width: 50%;
    margin-left: 188px;
}*/




div.botao{
    text-align: center;
}

</style>


             

<br>
<div class="container titulo" >
    <h5 class="text-uppercase font-weight-light text-monospace">Todos os chamados solicitados</h5>
</div>

<br>
<br>

<div class="container" >
<a href="/" >
        
    <!-- <i class="fas fa-plus" aria-hidden="true"></i> Solicitar-->
     <button type="button" class="btn btn-primary botao text-uppercase font-weight-light text-monospace">Volte para Home</button>
 
</a>
<br>
</div>

<br>
<br>

       
            <div class="col-12 container ajustePesquisar" >
                <input class="form-control container" id="myInput" type="text" placeholder="Pesquise por registros de qualquer campo..." >
                <!--<i class="fas fa-search" ></i>-->
             </div>
        
             <br>
        
        
  

    <br>
    <br>
    <div class="container" >
        <h5 class="text-uppercase font-weight-light text-monospace">Listagem abaixo</h5>
    </div>
    <br>
    <br>
 
    <div class="container" >
    <div class="tabela">
        <table class="table">
            <thead>
            <tr> 
                <th style="text-align: center;" >Solicitante</th>
                <th style="text-align: center;" >Data</th>
                <th style="text-align: center;" >Título</th>
                <th style="text-align: center;" >Descrição</th>
                <th style="text-align: center;" >Status</th>
                <!--<th style="text-align: center;" >Anexo</th>-->
                <th></th>
                <th></th>
                
            </tr>
            </thead>

            {% if messages %}
            <!--Messagens de alerta de interação ao editar e excluir item-->
                <ul class="messages" >
                    {% for message in messages %}
                        <li {% if message.tags  %}class="alert alert-{{message.tags}}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>

            {% endif %}

            <tbody id="myTable" class="alinhar">
     
            {% for chamado in chamados %}

            <tr>
                <td style="text-align: center;" >{{chamado.user}}</td>
                <td style="text-align: center;" >{{chamado.created_at}}</td>
                <td style="text-align: center;" >{{chamado.titulo}}</td>
                <td style="text-align: center;" >{{chamado.descrição}}</td>
                <td style="text-align: center;" >{{chamado.Status}}</a></td>
                <!--<td style="text-align: center;" ><a href="/midia/{{chamado.Arquivo}}" >Ver</a></td>-->
           

            </tr>

            {% endfor %}

            </tbody>
        </table>

        
        <div class="pagination" >
            <span class="step-links" >
                <!--Lógica para página anterior-->
                {% if chamados.has_previous %}
                    <a href="?page={{ chamados.previous_page_number }}" ><i class="fas fa-arrow-left" ></i></a>
                {% endif %}

                <!--Span mostrando a página atual do usuário-->
                <span class="current" >
                    {{ chamados.number }} de {{ chamados.paginator.num_pages }}
                </span>

                <!--Lógica para página posterior-->
                {% if chamados.has_next %}
                    <a href="?page={{ chamados.next_page_number }}" ><i class="fas fa-arrow-right" ></i></a>
                {% endif %}
            </span>
        </div>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        
        </div>
    </div>

        <script>
            $(document).ready(function(){
            $("#myInput").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function() {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
            });
        </script>
    

{% endblock %}

chamados_gerais/templates/chamados/edit2.html
{% extends 'base3.html' %}
{% load crispy_forms_tags %}

{% block title %}Editando{% endblock %}

{% block content %}


    <style>

    .ajuste{
       width: 400px;
    }
    
    
    </style>
    

<div class="offset-1 col-10 list-div ajuste">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-primary botao text-uppercase font-weight-light text-monospace" value="Editar">
    </form>
</div>


{% endblock %}


<!--<div class="offset-1 col-10 list-div ajuste">
    <form method="POST" enctype="multipart/form-data">
        
        <input type="text" name="Título" placeholder="Enter a title">
        <input type="text" name="Descrição" placeholder="Enter a descrição">
        <input type="file" name="Arquivo">
        <input type="text" name="Status">
        
        {% csrf_token %}
       
        <input type="submit" class="btn btn-primary botao text-uppercase font-weight-light text-monospace" value="Editar">
    </form>
</div>




    <style>

    .ajuste{
       width: 400px;
    }
    
    
    </style>
    

<div class="offset-1 col-10 list-div ajuste">
    <form method="POST" enctype="multipart/form-data">
        
        <input type="text" name="Título" value="Lazer 2" maxlength="255" class="textinput textInput form-control" required="" id="id_Título">
        <textarea name="Descrição" cols="40" rows="10" class="textarea form-control" required="" id="id_Descrição">4gg4tg4tg4 2</textarea>
        <input type="file" name="Arquivo" class="clearablefileinput form-control-file" id="id_Arquivo">
        <select name="Status" class="select form-control" required="" id="id_Status"> <option value="">---------</option> <option value="Solicitado" selected="">Solicitado</option> <option value="Em_andamento">Em_andamento</option> <option value="Concluído">Concluído</option>
        </select>
        {% csrf_token %}
      
        <input type="submit" class="btn btn-primary botao text-uppercase font-weight-light text-monospace" value="Editar">
    </form>
</div>





<div class="offset-1 col-10 list-div ajuste">
    <form method="POST" enctype="multipart/form-data">
        
        <input type="text" name="Título" placeholder="Enter a title">
        <input type="text" name="Descrição" placeholder="Enter a descrição">
        <input type="file" name="Arquivo">
        <input type="text" name="Status">
        
        {% csrf_token %}
       
        <input type="submit" class="btn btn-primary botao text-uppercase font-weight-light text-monospace" value="Editar">
    </form>
</div>-->





-->

chamados_gerais/templates/chamados/editChamado.html
{% extends 'base2.html' %}
{% load crispy_forms_tags %}

{% block title %}Editando{% endblock %}

{% block content %}


<style>

    .ajuste{
       width: 400px;
    }
    
    
    </style>
    


<div class="offset-1 col-10 list-div ajuste">
   <h5 class="text-uppercase font-weight-light text-monospace">Editar o chamado: {{chamado.Título}}</h5>
   <br>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <input type="submit" class="btn btn-primary botao text-uppercase font-weight-light text-monospace" value="Editar">
    </form>
</div>


{% endblock %}